<?php

use Magento\Framework\App\Action\Action;

/** @var $block \Magento\Catalog\Block\Product\ListProduct */

$_productCollection = $block->getLoadedProductCollection();
if (!$_productCollection->count()) return;

$_helper = $this->helper('Magento\Catalog\Helper\Output');

$viewMode     = 'grid';
$image        = 'category_page_grid';
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
$pos          = $block->getPositioned();

$nextPage = ($_productCollection->getCurPage() == $_productCollection->getLastPageNumber()) ? 0 : $_productCollection->getCurPage(+1);

$config         = $this->getWidgetCfg();
$timer          = $config['timer']    ?? '';
$showCart       = $config['cart']     ?? '';
$showCompare    = $config['compare']  ?? '';
$showWishlist   = $config['wishlist'] ?? '';
$showReview     = $config['review']   ?? '';
$identifier     = $config['identifier']?? '';
$swatchesRender = $block->getLayout()->createBlock('Magento\Swatches\Block\Product\Renderer\Listing\Configurable')->setTemplate('Magiccart_Magicproduct::product/listing/renderer.phtml');

$pageConfig     = $this->helper('Silk\Page\Helper\Magiccart\Magicproduct')->buildPageConfig($config);
$slide          = $pageConfig['slide'];
$rows           = $pageConfig['rows'];
$padding        = $pageConfig['padding'] ? $pageConfig['padding'] : '15';
$containerClass = 'products wrapper '.$viewMode.' products-'.$viewMode;
$olClass        = 'list items product-items';
$liClass        = 'item product product-item';
if ($slide) {
    $containerClass .= ' swiper';
    $olClass .= ' swiper-wrapper';
    $liClass .= ' swiper-slide';
}
if (!empty($pageConfig['responsiveClass'])) {
    $olClass .= ' '.join(' ', $pageConfig['responsiveClass']);
}
?>
<div class="<?php /* @escapeNotVerified */ echo $containerClass; ?>" style="margin-left: -<?= $padding ?>px; margin-right: -<?= $padding ?>px;"
    data-next-page="<?php /* @escapeNotVerified */ echo $nextPage ?>"
    <?php if (!empty($pageConfig['scriptConfig'])) : ?>data-mage-init='<?= json_encode($pageConfig['scriptConfig']) ?>'<?php endif; ?>>
    <ol class="<?php /* @escapeNotVerified */ echo $olClass; ?>" data-identifier="<?= $identifier ?>"
        style="padding:0 <?= $padding / 2 ?>px;<?php if (!$slide) : ?>flex-wrap: wrap;<?php endif; ?>"
    >
        <?php $iterator = 1; ?>
        <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
        <?php foreach ($_productCollection as $_product): ?>
        <?php $mod = $iterator++ % $rows; ?>
            <?php if (!$slide || $rows === 1 || $mod === 1) : ?>
            <li class="<?php /* @escapeNotVerified */ echo $liClass; ?>" style="width: auto; margin-left: 0; padding: 0 <?= $padding / 2 ?>px;">
            <?php endif; ?>
                <div class="product-item-info" data-container="product-grid" data-sku="<?= $_product->getSku() ?>"
                    style="width: 100%;<?= (!$slide || $mod !== 0) ? ' margin-bottom:'.$padding.'px' : '' ?>">
                    <?php
                        $fromDate = $_product->getData('news_from_date');
                        $toDate = $_product->getData('news_to_date');
                        $isNew = false;
                        if ($fromDate){
                            $fromDate = strtotime($fromDate);
                            $toDate = strtotime($toDate);
                            $now = strtotime(date("Y-m-d H:i:s"));

                            if ($toDate){
                                if ($fromDate <= $now && $now <= $toDate) $isNew = true;
                            } else {
                                if ($fromDate <= $now) $isNew = true;
                            }
                        } else if($toDate) {
                            $toDate = strtotime($toDate);
                            $now = strtotime(date("Y-m-d H:i:s"));
                            if ($now <= $toDate) $isNew = true;
                        }
                        if ($isNew):
                    ?><div class="product-label"><?= __('NEW') ?></div><?php endif; ?>
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;' . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <div class="images-container">
                        <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>"
                            class="product photo product-item-photo" tabindex="-1">
                            <?php echo $productImage->toHtml(); ?>
                        </a>
                    </div>
                    <div class="product details product-item-details">
                        <?php if ($_product->getCouponCode()):?><div class="coupon-tag">Coupon</div><?php endif; ?>
                        <?php
                        $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link" href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                            </a>
                        </strong>
                        <?php echo $showReview ? $block->getReviewsSummaryHtml($_product, $templateType) : ''; ?>
                        <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                        <?php echo $swatchesRender->setProduct($_product)->toHtml() ?>
                        <?php echo $block->getProductDetailsHtml($_product); ?>
                        <div class="product-item-inner">
                            <?php if ($showWishlist || $showCompare || $showCart) : ?>
                                <div class="product actions product-item-actions" <?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                    <?php if ($showCart) : ?>
                                        <div class="actions-primary" <?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                            <?php if ($_product->isSaleable()) : ?>
                                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                                    <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                                    <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                    <?php echo $block->getBlockHtml('formkey') ?>
                                                    <button type="submit" title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>" class="action tocart primary">
                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                    </button>
                                                </form>
                                            <?php else : ?>
                                                <?php if ($_product->getIsSalable()) : ?>
                                                    <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                <?php else : ?>
                                                    <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                    <?php if (false && ($showWishlist || $showCompare)) : ?>
                                        <div data-role="add-to-links" class="actions-secondary" <?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist) : ?>
                                                <a href="#" class="action towishlist" title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>' data-action="add-to-wishlist" role="button">
                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                                </a>
                                            <?php endif; ?>
                                            <?php if ($showCompare) :
                                                $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                            ?>
                                                <a href="#" class="action tocompare" title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>" data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>' role="button">
                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                                                </a>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            <?php if (!$slide || $mod === 0) : ?>
            </li>
            <?php endif; ?>
        <?php endforeach; ?>
    </ol>
    <?php if ($slide && $pageConfig['arrows']) : ?>
        <div class="swiper-button-prev"></div>
        <div class="swiper-button-next"></div>
    <?php endif; ?>
</div>
