<?php

use Magento\Framework\App\Action\Action;

/** @var $block \Magento\Catalog\Block\Product\ListProduct */

$_productCollection = $block->getLoadedProductCollection();

if (!$_productCollection->count()) return;

$image = 'category_page_grid';
$config = $this->getWidgetCfg();
$outputHelper = $this->helper('Magento\Catalog\Helper\Output');
$magicHelper = $this->helper('Silk\Page\Helper\Magiccart\Magicproduct');
?>
<div class="products wrapper grid products-grid" data-id="<?= $config['identifier'] ?>">
    <ol class="list items product-items" data-identifier="<?= $config['identifier'] ?>">
        <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
        <?php $iterator = 0; ?>
        <?php foreach ($_productCollection as $_product) : ?>
            <?php $iterator++; ?>
            <?php if ($iterator > 4) { break; } ?>
            <li class="item product product-item">
                <div class="product-item-info" data-sku="<?= $_product->getSku() ?>">
                    <?php if ($magicHelper->isNew($_product)) : ?><div class="product-label"><?= __('NEW') ?></div><?php endif; ?>
                    <?php $productImage = $block->getImage($_product, $image); ?>
                    <div class="images-container" width="<?= $productImage->getWidth() ?>" height="<?= $productImage->getHeight() ?>">
                        <a href="<?= $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                            <?php echo $productImage->toHtml(); ?>
                        </a>
                    </div>
                    <div class="product details product-item-details">
                        <strong class="product name product-item-name">
                            <a class="product-item-link" href="<?= $_product->getProductUrl() ?>">
                                <?= $outputHelper->productAttribute($_product, $_product->getName(), 'name'); ?>
                            </a>
                        </strong>
                        <?= $block->getProductPrice($_product) ?>
                        <div class="product-item-inner">
                            <div class="product actions product-item-actions">
                                <div class="actions-primary">
                                    <?php if ($_product->isSaleable()) : ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" action="<?= $postParams['action']; ?>" method="post">
                                            <input type="hidden" name="product" value="<?= $postParams['data']['product']; ?>">
                                            <input type="hidden" name="<?= Action::PARAM_NAME_URL_ENCODED; ?>" value="<?= $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                            <?php echo $block->getBlockHtml('formkey') ?>
                                            <button type="submit" title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>" class="action tocart primary">
                                                <span><?= __('Add to Cart') ?></span>
                                            </button>
                                        </form>
                                    <?php else : ?>
                                        <?php if ($_product->getIsSalable()) : ?>
                                            <div class="stock available"><span><?= __('In stock') ?></span></div>
                                        <?php else : ?>
                                            <div class="stock unavailable"><span><?= __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
        <?php endforeach; ?>
    </ol>
</div>
