<?php $viewModel = $block->getViewModel(); ?>
<?php $_telephone = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Telephone::class) ?>
<?php $_country_id = $block->getAttributeData()->getFrontendLabel('country_id'); ?>
<?php $_street = $block->getAttributeData()->getFrontendLabel('street'); ?>
<?php $_city = $block->getAttributeData()->getFrontendLabel('city'); ?>
<?php $_region = $block->getAttributeData()->getFrontendLabel('region'); ?>
<?php $_selectRegion = 'Please select a region, state or province.'; ?>
<?php $_displayAll = $block->getConfig('general/region/display_all'); ?>
<?php $_cityValidationClass = $viewModel->addressGetAttributeValidationClass('city'); ?>
<?php $_postcodeValidationClass_value = $viewModel->addressGetAttributeValidationClass('postcode'); ?>
<?php $_postcodeValidationClass = $_postcodeValidationClass_value; ?>
<?php $_streetValidationClass = $viewModel->addressGetAttributeValidationClass('street'); ?>
<?php $_streetValidationClassNotRequired = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
<?php $_regionValidationClass = $viewModel->addressGetAttributeValidationClass('region'); ?>

<form class="form"
    enctype="multipart/form-data"
    id="form-address-edit"
    action=""
    data-hasrequired="<?= $escaper->escapeHtmlAttr(__('* Required Fields')) ?>">
    <fieldset class="fieldset">
        <?= $block->getBlockHtml('formkey') ?>
        <?= $block->getNameBlockHtml() ?>

        <div class="field street required">
            <label for="street_1" class="label"><span><?= /* @noEscape */ $_street ?></span></label>
            <div class="control">
                <div class="field primary">
                    <label for="street_1" class="label">
                        <span>
                            <?= $escaper->escapeHtml(__('Street Address: Line %1', 1)) ?>
                        </span>
                    </label>
                </div>
                <input
                    type="text"
                    name="street[]"
                    value="<?= $escaper->escapeHtmlAttr($block->getStreetLine(1)) ?>"
                    title="<?= /* @noEscape */ $_street ?>"
                    id="street_1"
                    class="input-text <?= $escaper->escapeHtmlAttr($_streetValidationClass) ?>" />
                <div class="nested">
                    <?php for ($_i = 1, $_n = $viewModel->addressGetStreetLines(); $_i < $_n; $_i++): ?>
                    <div class="field additional">
                        <label class="label" for="street_<?= /* @noEscape */ $_i + 1 ?>">
                            <span><?= $escaper->escapeHtml(__('Street Address: Line %1', $_i + 1)) ?></span>
                        </label>
                        <div class="control">
                            <input
                                type="text"
                                name="street[]"
                                value="<?= $escaper->escapeHtmlAttr($block->getStreetLine($_i + 1)) ?>"
                                title="<?= $escaper->escapeHtmlAttr(__('Street Address %1', $_i + 1)) ?>"
                                id="street_<?= /* @noEscape */ $_i + 1 ?>"
                                class="input-text
                                <?= $escaper->escapeHtmlAttr($_streetValidationClassNotRequired) ?>" />
                        </div>
                    </div>
                    <?php endfor; ?>
                </div>
            </div>
        </div>

        <?php if ($viewModel->addressIsVatAttributeVisible()): ?>
            <div class="field taxvat">
                <label class="label" for="vat_id">
                    <span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('vat_id') ?></span>
                </label>
                <div class="control">
                    <input
                        type="text"
                        name="vat_id"
                        value="<?= $escaper->escapeHtmlAttr($block->getAddress()->getVatId()) ?>"
                        title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('vat_id') ?>"
                        class="input-text <?= $escaper->escapeHtmlAttr($_vatidValidationClass) ?>"
                        id="vat_id">
                </div>
            </div>
        <?php endif; ?>

        <div class="field country required">
            <label class="label" for="country">
                <span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('country_id') ?></span>
            </label>
            <div class="control">
                <?= $block->getCountryHtmlSelect() ?>
            </div>
        </div>

        <div class="field region required">
            <label class="label" for="region_id">
                <span><?= /* @noEscape */ $_region ?></span>
            </label>
            <div class="control">
                <select
                    id="region_id"
                    name="region_id"
                    title="<?= /* @noEscape */ $_region ?>"
                    class="validate-select region_id"
                    <?= /* @noEscape */ !$_displayAll ? ' disabled="disabled"' : '' ?>>
                    <option value=""><?= $escaper->escapeHtml(__($_selectRegion)) ?></option>
                </select>
                <input
                    type="text"
                    id="region"
                    name="region"
                    value="<?= $escaper->escapeHtmlAttr($block->getRegion()) ?>"
                    title="<?= /* @noEscape */ $_region ?>"
                    class="input-text validate-not-number-first <?= $escaper->escapeHtmlAttr($_regionValidationClass) ?>"
                    <?= !$_displayAll ? ' disabled="disabled"' : '' ?> />
            </div>
        </div>

        <div class="field city required">
            <label class="label" for="city">
                <span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?></span>
            </label>
            <div class="control">
                <input
                    type="text"
                    name="city"
                    value="<?= $escaper->escapeHtmlAttr($block->getAddress()->getCity()) ?>"
                    title="<?= $escaper->escapeHtmlAttr(__('City')) ?>"
                    class="input-text <?= $escaper->escapeHtmlAttr($_cityValidationClass) ?>"
                    id="city">
            </div>
        </div>

        <div class="field zip required">
            <label class="label" for="zip">
                <span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?></span>
            </label>
            <div class="control">
                <input
                    type="text"
                    name="postcode"
                    value="<?= $escaper->escapeHtmlAttr($block->getAddress()->getPostcode()) ?>"
                    title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?>"
                    id="zip"
                    class="input-text validate-zip-international
                    <?= $escaper->escapeHtmlAttr($_postcodeValidationClass) ?>">
                <div role="alert" class="message warning">
                    <span></span>
                </div>
                <?= /* @noEscape */ $secureRenderer->renderStyleAsTag("display: none;", 'div.message.warning') ?>
            </div>
        </div>

        <?php if ($_telephone->isEnabled()): ?>
            <?= $_telephone->setTelephone($block->getAddress()->getTelephone())->toHtml() ?>
        <?php endif ?>
    </fieldset>
</form>

<script type="text/x-magento-init">
    {
        "#form-address-edit": {
            "Magento_Customer/js/addressValidation": {
                "postCodes": <?= /* @noEscape */ $block->getPostCodeConfig()->getSerializedPostCodes() ?>
            }
        },
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?= /* @noEscape */ $_displayAll ? 'true' : 'false' ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-address-edit",
                "regionJson": <?= /* @noEscape */ $viewModel->dataGetRegionJson() ?>,
                "defaultRegion": "<?= (int) $block->getRegionId() ?>",
                "countriesWithOptionalZip": <?= /* @noEscape */ $viewModel->dataGetCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>
