<?php

use Magento\Framework\App\Action\Action;

/** @var \Magento\Catalog\Block\Product\ListProduct $block */

$_productCollection = $block->getLoadedProductCollection();
if (!$_productCollection->count()) return;

$_helper = $this->helper('Magento\Catalog\Helper\Output');

$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
$image = 'category_page_grid';

$cfg = $block->getCfg();
if (!empty($cfg['utmKey'])) {
    $utmKey = $cfg['utmKey'];
}
?>
<div class="products wrapper grid products-grid style__align-left">
    <ol class="list items product-items">
        <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
        <?php foreach ($_productCollection as $_product): ?>
            <li class="item product product-item" data-sku="<?= $_product->getSku() ?>" data-type="<?= $_product->getTypeId() ?>">
                <div class="product-item-info" data-container="product-grid">
                    <?php $productImage = $block->getImage($_product, $image); ?>
                    <?php $productUrl = $_product->getProductUrl(); ?>
                    <?php if (!empty($utmKey)) {
                        $productUrl = $productUrl . '?utm_term=' . $utmKey . '+'. $_product->getSku();
                    }?>
                    <div class="images-container">
                        <a href="<?= $productUrl ?>"
                            class="product photo product-item-photo" tabindex="-1" target="_blank">
                            <?php echo $productImage->toHtml(); ?>
                        </a>
                    </div>
                    <div class="product details product-item-details">
                        <strong class="product name product-item-name">
                            <a class="product-item-link" href="<?= $productUrl ?>" target="_blank">
                                <?= $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                            </a>
                        </strong>
                        <?= $block->getProductPrice($_product) ?>
                        <div class="with-code"><span></span></div>
                        <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                        <div class="actions promotion-product-m-actions">
                            <?php if ($_product->isSaleable()) : ?>
                                <div class="progress"><div class="progress__bar"><div class="progress__fill"></div></div></div>
                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                <form class="tocart-form" data-role="tocart-form" action="<?= $postParams['action']; ?>" method="post">
                                    <input type="hidden" name="product" value="<?= $postParams['data']['product']; ?>">
                                    <input type="hidden" name="qty" value="1">
                                    <input type="hidden" name="<?= Action::PARAM_NAME_URL_ENCODED; ?>" value="<?= $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                    <?php echo $block->getBlockHtml('formkey') ?>
                                    <button type="submit" class="action outline-primary tocart"><span><?= __('Add to Cart') ?></span></button>
                                    <button type="button" class="action primary buynow" data-default-label="<?= __('Buy Now') ?>"
                                        <?php if ($_product->getTypeId() == \Magento\ConfigurableProduct\Model\Product\Type\Configurable::TYPE_CODE): ?>
                                        data-type="configurable" data-id="<?= $postParams['data']['product']; ?>"
                                        <?php endif; ?>
                                    ><?= __('Buy Now') ?></button>
                                </form>
                                <?php if ($_product->getTypeId() == \Magento\ConfigurableProduct\Model\Product\Type\Configurable::TYPE_CODE): ?>
                                <?php else: ?>
                                <?php endif; ?>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </li>
        <?php endforeach; ?>
        <?php if (!empty($cfg['gallery'])): ?><li class="gallery"><div class="gallery-content"></div></li><?php endif; ?>
    </ol>
</div>
